# This file was generated by GoReleaser. DO NOT EDIT.
cask "cws-mcp" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "ef367e0afb45e2d6395385b757c934d7f794e40b337d23357eec25d4df6e013b"
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v#{version}/cws-mcp_darwin_amd64.tar.gz",
        verified: "github.com/vaughnbosu/cws-mcp/"
    end
    on_arm do
      sha256 "afc8a6a7fcd09d68034d2334ad3a3732254c9bd0fc9671a038b284e240b4417d"
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v#{version}/cws-mcp_darwin_arm64.tar.gz",
        verified: "github.com/vaughnbosu/cws-mcp/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e477941ad31ecafc3d7198b230400818b56fa386c339e1f917bd13aca3cec77d"
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v#{version}/cws-mcp_linux_amd64.tar.gz",
        verified: "github.com/vaughnbosu/cws-mcp/"
    end
    on_arm do
      sha256 "45aa7da54a81de5cf4c6cec977a50723b64187ed5d4b6e058135c7fb924ecaa7"
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v#{version}/cws-mcp_linux_arm64.tar.gz",
        verified: "github.com/vaughnbosu/cws-mcp/"
    end
  end

  name "cws-mcp"
  desc "MCP server for managing Chrome Web Store extensions"
  homepage "https://github.com/vaughnbosu/cws-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cws-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cws-mcp"]
    end
  end

  # No zap stanza required

end
