# This file was generated by GoReleaser. DO NOT EDIT.
cask "cws" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "a48bf169607b54c7d815edf26fed4bc119a8d4c50709209001dfcf035382b327"
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v#{version}/cws_darwin_amd64.tar.gz",
        verified: "github.com/vaughnbosu/cws-cli/"
    end
    on_arm do
      sha256 "1d91ddddbcffd9ff8c071c3a3e88c079b636085b4483b3a12cd349470044a690"
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v#{version}/cws_darwin_arm64.tar.gz",
        verified: "github.com/vaughnbosu/cws-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "51ffd377293457b506eae5f6db33cd2bc999fb4cbebdad6bfbe88fda09983310"
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v#{version}/cws_linux_amd64.tar.gz",
        verified: "github.com/vaughnbosu/cws-cli/"
    end
    on_arm do
      sha256 "ad9bb117734f52d0670f57b9a1d7d84fafa520e324cd0b9737030831eaa4c0ae"
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v#{version}/cws_linux_arm64.tar.gz",
        verified: "github.com/vaughnbosu/cws-cli/"
    end
  end

  name "cws"
  desc "A CLI for managing Chrome Web Store extensions"
  homepage "https://vaughnbosu.github.io/cws-cli/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cws"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cws"]
    end
  end

  # No zap stanza required

end
