# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwsMcp < Formula
  desc "MCP server for managing Chrome Web Store extensions"
  homepage "https://github.com/vaughnbosu/cws-mcp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.0/cws-mcp_darwin_amd64.tar.gz"
      sha256 "26663ace9828ebbd2900ce25de189864a7a036f783d93ae8d59226ddfdf2b4f4"

      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.0/cws-mcp_darwin_arm64.tar.gz"
      sha256 "d0d04c35db3633d324260d0c4179c7fb7b6d91cbd3c1544288094f060982a670"

      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.0/cws-mcp_linux_amd64.tar.gz"
      sha256 "399b7327f8764a2d4f44110b1217ef1e8be4083608d510dd6a28ff4355d5764d"
      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.0/cws-mcp_linux_arm64.tar.gz"
      sha256 "bdd98615bfeaec7a6aa37d562d47ec0e23d9e23349035ffd69b36bf5069fa9d5"
      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cws-mcp -version")
  end
end
