# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwsMcp < Formula
  desc "MCP server for managing Chrome Web Store extensions"
  homepage "https://github.com/vaughnbosu/cws-mcp"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.1/cws-mcp_darwin_amd64.tar.gz"
      sha256 "6fad4dc774f000be64c962269d25e8cf776e3e88085c002d48c0ede266378f93"

      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.1/cws-mcp_darwin_arm64.tar.gz"
      sha256 "39038f87c02253b6036f7b6562402f0cc925d1742ba745211542a557a52f2f3b"

      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.1/cws-mcp_linux_amd64.tar.gz"
      sha256 "35c8c2f140df65bb8d8520696582e8028cc23a8ba501416ea0d5624c5ada84aa"
      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.1/cws-mcp_linux_arm64.tar.gz"
      sha256 "f4c98b8b4cfbdbe9217f011b597521ac35ac459cfbe5e108124d156c26db83f1"
      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cws-mcp -version")
  end
end
