# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwsMcp < Formula
  desc "MCP server for managing Chrome Web Store extensions"
  homepage "https://github.com/vaughnbosu/cws-mcp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.0/cws-mcp_darwin_amd64.tar.gz"
      sha256 "e786a5fbdede5d69d5e8242b0230a1ee45d86a9fd71c84704e992e439364fd6c"

      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.0/cws-mcp_darwin_arm64.tar.gz"
      sha256 "1986f88aaea4c9a773355b2c4892f308590686106d87484c42b7b589ebfc9bdc"

      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.0/cws-mcp_linux_amd64.tar.gz"
      sha256 "4a34550acd9815e13d6986fbd81c7259ff5dbbb0ace55f8095718b98d17a37d4"
      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-mcp/releases/download/v0.1.0/cws-mcp_linux_arm64.tar.gz"
      sha256 "81e7d4a436e5ff5b5641339905a88bb9e4e587c4642a2ee0953e8b10d5f5f090"
      define_method(:install) do
        bin.install "cws-mcp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cws-mcp -version")
  end
end
