# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cws < Formula
  desc "A CLI for managing Chrome Web Store extensions"
  homepage "https://vaughnbosu.github.io/cws-cli/"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.3.0/cws_darwin_amd64.tar.gz"
      sha256 "e5c3dd43110e5d03a9000ea61c1fb2a1088903df90484af9ff32eeeb50955d66"

      define_method(:install) do
        bin.install "cws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.3.0/cws_darwin_arm64.tar.gz"
      sha256 "982626ebe398e765be41c3338735696c1482cce30f03b3d7bfe28db13198538b"

      define_method(:install) do
        bin.install "cws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.3.0/cws_linux_amd64.tar.gz"
      sha256 "1c13330754280412c997609f30c1de84ef6077f4d42900cdee215f3b790969fe"
      define_method(:install) do
        bin.install "cws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.3.0/cws_linux_arm64.tar.gz"
      sha256 "9896f37d51c6f06c527600d35f9f624f6449a1558626b1daa11db640d16c74b7"
      define_method(:install) do
        bin.install "cws"
      end
    end
  end

  test do
    system "#{bin}/cws", "version"
  end
end
