# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cws < Formula
  desc "A CLI for managing Chrome Web Store extensions"
  homepage "https://vaughnbosu.github.io/cws-cli/"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.3.0/cws_darwin_amd64.tar.gz"
      sha256 "85643499603d8fc43f7219194f478d021ff14428d58e7ecf6b37b66866e461c7"

      define_method(:install) do
        bin.install "cws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.3.0/cws_darwin_arm64.tar.gz"
      sha256 "16f8589e89cf42aa4733b72cbfe725bf368d05eb606107dea66f3394bed37145"

      define_method(:install) do
        bin.install "cws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.3.0/cws_linux_amd64.tar.gz"
      sha256 "20d3fd2faf2d7fda283f209311a3b737c8737fc5ea548910048b3806487af38e"
      define_method(:install) do
        bin.install "cws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.3.0/cws_linux_arm64.tar.gz"
      sha256 "49fd11ea45bf5158c065b9eab22eb1cdf066fc99e885be72544dd94ad192dc51"
      define_method(:install) do
        bin.install "cws"
      end
    end
  end

  test do
    system "#{bin}/cws", "version"
  end
end
