# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cws < Formula
  desc "A CLI for managing Chrome Web Store extensions"
  homepage "https://vaughnbosu.github.io/cws-cli/"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.2.0/cws_darwin_amd64.tar.gz"
      sha256 "52671c20342f0e761c5b777303ea4bf624ab7d3eace512c796eec64aa6b35c34"

      define_method(:install) do
        bin.install "cws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.2.0/cws_darwin_arm64.tar.gz"
      sha256 "82c8b5f16e958214bdbb5f564b80034503329f1f9c2f41772411329126b6ebfa"

      define_method(:install) do
        bin.install "cws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.2.0/cws_linux_amd64.tar.gz"
      sha256 "75b31f41a4b40939e0649ecdef5e1ab30efd4feafcd0cfe089d8001ca20cee86"
      define_method(:install) do
        bin.install "cws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaughnbosu/cws-cli/releases/download/v1.2.0/cws_linux_arm64.tar.gz"
      sha256 "e4c84b7e6d00ae56b1f7a4deacc0ed8bdf8ffa354bebf52f17d17fc690a947bd"
      define_method(:install) do
        bin.install "cws"
      end
    end
  end

  test do
    system "#{bin}/cws", "version"
  end
end
